name: Delete Older Releases

on:
  push:
    branches:
      - main

jobs:
  delete_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          repo: secondnetwork/kompass # Replace <owner> and <repoName> with your repository details
          keep_latest: 5 # Set to 0 to delete all releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}