name: Delete Older Releases

on:
  workflow_dispatch:

jobs:
  delete_releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Nats-ji/delete-old-releases@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        keep-count: 5
        keep-old-minor-releases: true
        keep-old-minor-releases-count: 1
