name: Delete Older Releases

on:
  workflow_dispatch:

jobs:
  delete_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 5
          keep_min_download_counts: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
